# Generated by Django 5.2.5 on 2025-08-23 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_cartitem_user_alter_cartitem_cart'),
        ('orders', '0004_orderproduct_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='cart_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carts.cartitem'),
        ),
    ]
