# Generated by Django 5.2.5 on 2025-08-24 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_orderproduct_cart_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='cart_item',
        ),
    ]
